[ci] Trying out a different release action
[skip ci]

diff --git a/.github/workflows/stage-release.yml b/.github/workflows/stage-release.yml
--- a/.github/workflows/stage-release.yml
+++ b/.github/workflows/stage-release.yml
@@ -26,8 +26,6 @@ jobs:
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
-        with:
-          fetch-depth: '0'
       - name: Extract version from branch name
         if: github.event.pull_request.merged == true
         run: |
@@ -42,10 +40,10 @@ jobs:
         run: |
           git config --local user.email "selenium-ci@users.noreply.github.com"
           git config --local user.name "Selenium CI Bot"
-      - name: Tag Release
-        run: |
-          git tag selenium-${{ env.VERSION }} || echo "Tag already exists"
-          git push origin selenium-${{ env.VERSION }} || echo "Tag already exists remotely"
+      #      - name: Tag Release
+      #        run: |
+      #          git tag selenium-${{ env.VERSION }} || echo "Tag already exists"
+      #          git push origin selenium-${{ env.VERSION }} || echo "Tag already exists remotely"
       - name: Setup Java
         uses: actions/setup-java@v3
         with:
@@ -55,21 +53,37 @@ jobs:
         run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
       - name: Build and Stage Packages
         run: ./go all:package[--config=release]
-      - name: Update Nightly Tag to Remove pre-release
-        run: |
-          git fetch --tags
-          git tag -d nightly || echo "Nightly tag not found"
-          git tag nightly
-          git push origin refs/tags/nightly --force
+      #      - name: Update Nightly Tag to Remove pre-release
+      #        run: |
+      #          git fetch --tags
+      #          git tag -d nightly || echo "Nightly tag not found"
+      #          git tag nightly
+      #          git push origin refs/tags/nightly --force
       - name: Generate Draft Release
-        uses: softprops/action-gh-release@v2
+        uses: ncipollo/release-action@v1
         with:
-          name: Selenium ${{ env.VERSION }}
-          tag_name: selenium-${{ env.VERSION }}
+          artifacts: "build/dist/*.*"
+          bodyFile: "scripts/github-actions/release-notes.md"
           draft: true
-          generate_release_notes: true
+          generateReleaseNotes: true
+          name: Selenium ${{ env.VERSION }}
           prerelease: false
-          files: build/dist/*.*
+          skipIfReleaseExists: true
+          tag: selenium-${{ env.VERSION }}
+          commit: trunk
+  #      - name: Generate Draft Release
+  #        uses: softprops/action-gh-release@v2
+  #        with:
+  #          name: Selenium ${{ env.VERSION }}
+  #          body: |
+  #            ## Detailed Changelogs by Component
+  #            <img src="https://www.selenium.dev/images/programming/java.svg" width="20" height="20"> **[Java](https://github.com/SeleniumHQ/selenium/blob/trunk/java/CHANGELOG)** &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;<img src="https://www.selenium.dev/images/programming/python.svg" width="20" height="20"> **[Python](https://github.com/SeleniumHQ/selenium/blob/trunk/py/CHANGES)** &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;<img src="https://www.selenium.dev/images/programming/csharp.svg" width="20" height="20"> **[DotNet](https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/CHANGELOG)** &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;<img src="https://www.selenium.dev/images/programming/ruby.svg" width="20" height="20"> **[Ruby](https://github.com/SeleniumHQ/selenium/blob/trunk/rb/CHANGES)** &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;<img src="https://www.selenium.dev/images/programming/javascript.svg" width="20" height="20"> **[JavaScript](https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/CHANGES.md)** &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;<img src="https://www.selenium.dev/images/browsers/internet-explorer.svg" width="20" height="20"> **[IEDriver](https://github.com/SeleniumHQ/selenium/blob/trunk/cpp/iedriverserver/CHANGELOG)**
+  #            <br>
+  #          tag_name: selenium-${{ env.VERSION }}
+  #          draft: true
+  #          generate_release_notes: true
+  #          prerelease: false
+  #          files: build/dist/*.*
 
   update-documentation:
     needs: github-release
